trigger:
- main

pool:
  name: 'SH-TOOL'
  vmImage: 'ubuntu-latest'
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm uninstall @angular-devkit/build-angular
    rm -rf node_modules package-lock.json
    npm install --save-dev @angular-devkit/build-angular
    npm install --save-dev @angular-devkit/build-angular
    npm install -g @angular/cli
    npm ci
  displayName: 'Install Angular CLI and dependencies'

- script: |
    ng build --configuration production
  displayName: 'Build Angular project'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: 'drop'
  displayName: 'Publish build artifacts'