trigger:
- main

pool:
  name: 'SH-TOOL'
  vmImage: 'ubuntu-latest'
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    rm -rf node_modules package-lock.json
    npm install -g @angular/cli
    npm install
  displayName: 'Install Angular CLI and dependencies'

- script: |
    ng build --configuration production
  displayName: 'Build Angular project'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: 'drop'
  displayName: 'Publish build artifacts'